#!/bin/bash

# Output file
OUTPUT="Aetherbourne-Knowledge-Base.md"

# Start fresh
cat > "$OUTPUT" << EOF
# Aetherbourne Knowledge Base

> Auto-generated from the docs directory.
> Do not edit this file directly.

---

EOF

# Find all markdown files, sort them, and append them
find docs -type f -name "*.md" | sort | while read -r file
do
    title=$(basename "$file" .md)

    echo "" >> "$OUTPUT"
    echo "---" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "# $title" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    cat "$file" >> "$OUTPUT"

    echo "" >> "$OUTPUT"
done

echo "Generated $OUTPUT"